# Generated by Django 5.1 on 2024-08-25 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                ("region_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=256, null=True)),
                ("last_name", models.CharField(blank=True, max_length=256, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("upload_doc", models.BooleanField(default=False)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/profile_image/"
                    ),
                ),
                ("i_am_user", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superadmin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "INACTIVE"),
                            (1, "ACTIVE"),
                            (2, "DELETE"),
                            (3, "DRAFT"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
