# Generated by Django 5.1 on 2024-08-25 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_id",
            new_name="email",
        ),
    ]
