# Generated by Django 5.1 on 2024-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce_app", "0002_rename_email_id_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="description",
        ),
        migrations.RemoveField(
            model_name="user",
            name="i_am_user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="upload_doc",
        ),
        migrations.AddField(
            model_name="user",
            name="user_currency",
            field=models.IntegerField(
                blank=True, choices=[(0, "rupee"), (1, "dollar")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(0, "inactive"), (1, "active"), (2, "delete"), (3, "draft")],
                default=0,
            ),
        ),
    ]
