# Generated by Django 5.1 on 2024-08-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ecommerce_app",
            "0003_remove_user_description_remove_user_i_am_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_currency",
            field=models.CharField(
                blank=True,
                choices=[("rupee", "rupee"), ("dollar", "dollar")],
                max_length=10,
                null=True,
            ),
        ),
    ]
