# Generated by Django 5.1 on 2024-08-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce_app", "0004_alter_user_user_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(0, "inactive"), (1, "active"), (2, "delete"), (3, "draft")],
                default=1,
            ),
        ),
    ]
